#!/usr/bin/env bash
# warn-large-files.sh — PreToolUse hook for Edit|Write
# Blocks writes to build artifacts, binary files, and dependency directories.
# Exit 2 = block. Exit 0 = allow.

set -uo pipefail

INPUT=$(cat)

FILE_PATH=$(echo "$INPUT" | grep -oE '"file_path"\s*:\s*"[^"]*"' | head -1 | sed 's/.*: *"//;s/"$//')

if [[ -z "$FILE_PATH" ]]; then
  exit 0
fi

# --- Block dependency and build directories ---
REASON=""
case "$FILE_PATH" in
  node_modules/*|*/node_modules/*)
    REASON="Cannot write into node_modules/ — install dependencies via package manager instead." ;;
  vendor/*|*/vendor/*)
    REASON="Cannot write into vendor/ — use dependency manager instead." ;;
  dist/*|*/dist/*|build/*|*/build/*|.next/*|*/.next/*|.nuxt/*|*/.nuxt/*)
    REASON="Cannot write into build output directories — these are generated by the build process." ;;
  __pycache__/*|*/__pycache__/*)
    REASON="Cannot write into __pycache__/ — these are generated by Python." ;;
  .venv/*|*/.venv/*|venv/*|*/venv/*)
    REASON="Cannot write into virtual environment directories." ;;
  target/*|*/target/*)
    REASON="Cannot write into target/ — these are generated by the build tool (Cargo/Maven)." ;;
  .dart_tool/*|*/.dart_tool/*)
    REASON="Cannot write into .dart_tool/ — these are generated by Dart." ;;
  storage/framework/*|*/storage/framework/*)
    REASON="Cannot write into storage/framework/ — these are generated by Laravel." ;;
esac

if [[ -n "$REASON" ]]; then
  echo "BLOCKED: $REASON"
  exit 2
fi

# --- Block binary and archive file extensions ---
EXT="${FILE_PATH##*.}"
case "$EXT" in
  exe|dll|so|dylib|bin|o|a|lib)
    REASON="Cannot write binary executable/library files." ;;
  zip|tar|gz|bz2|xz|7z|rar|tgz)
    REASON="Cannot write archive files." ;;
  wasm)
    REASON="Cannot write WebAssembly binaries — these are compiled output." ;;
  pyc|pyo|class)
    REASON="Cannot write compiled bytecode files." ;;
  jpg|jpeg|png|gif|bmp|ico|webp|tiff|svg)
    REASON="Cannot write image files directly — use proper asset pipeline." ;;
  mp3|mp4|avi|mov|wav|flac|ogg|webm)
    REASON="Cannot write media files directly." ;;
  ttf|otf|woff|woff2|eot)
    REASON="Cannot write font files directly." ;;
  pdf)
    REASON="Cannot write PDF files directly." ;;
  sqlite|db|mdb)
    REASON="Cannot write database files directly." ;;
esac

if [[ -n "$REASON" ]]; then
  echo "BLOCKED: $REASON"
  exit 2
fi

exit 0
