"""File handling and marker detection for safe CLAUDE.md updates."""

from pathlib import Path
from typing import Tuple, Optional


MARKER = "<!-- Generated by /setup-claude-tools -->"


def has_marker(file_path: Path) -> bool:
    """Check if file contains the generation marker.

    Args:
        file_path: Path to the file

    Returns:
        True if marker is present, False otherwise
    """
    if not file_path.exists():
        return False

    try:
        content = file_path.read_text()
        return MARKER in content
    except Exception:
        return False


def is_custom_file(file_path: Path) -> bool:
    """Check if file exists and was not generated by our tools.

    Args:
        file_path: Path to the file

    Returns:
        True if file is custom (not generated), False otherwise
    """
    if not file_path.exists():
        return False
    return not has_marker(file_path)


def get_target_file(base_name: str = "CLAUDE.md") -> Tuple[Path, bool]:
    """Determine where to write the file.

    Args:
        base_name: Original filename (e.g., 'CLAUDE.md')

    Returns:
        Tuple of (target_path, is_sidecar) where is_sidecar indicates if we're
        writing to a sidecar file instead of the original
    """
    original = Path(base_name)

    # If file doesn't exist, use the original location
    if not original.exists():
        return original, False

    # If file has our marker, it's safe to update
    if has_marker(original):
        return original, False

    # File exists but is custom - write to sidecar
    sidecar = Path(f"{base_name}.setup-claude.md")
    return sidecar, True


def add_marker(content: str) -> str:
    """Add generation marker to content.

    Args:
        content: File content

    Returns:
        Content with marker appended
    """
    if content.endswith("\n"):
        return f"{content}\n{MARKER}\n"
    else:
        return f"{content}\n\n{MARKER}\n"


def format_output(
    target_path: Path,
    is_sidecar: bool,
    line_count: int,
    sections: list,
) -> str:
    """Format user-friendly output message.

    Args:
        target_path: Path where file was written
        is_sidecar: Whether writing to sidecar
        line_count: Number of lines in the file
        sections: List of sections in the file

    Returns:
        Formatted output message
    """
    msg = f"✓ {'CLAUDE.md suggestion' if is_sidecar else 'CLAUDE.md created'}: "
    msg += f"{target_path}\n"
    msg += f"  Lines: {line_count}/150\n"
    msg += f"  Sections: {', '.join(sections)}\n"

    if is_sidecar:
        msg += "\n📝 Note: CLAUDE.md already exists. Review the suggestion above and merge manually.\n"

    return msg


def count_lines(content: str) -> int:
    """Count non-empty lines in content."""
    return len([line for line in content.split("\n") if line.strip()])


def extract_sections(content: str) -> list:
    """Extract section names from markdown.

    Args:
        content: Markdown content

    Returns:
        List of section names
    """
    sections = []
    for line in content.split("\n"):
        if line.startswith("## "):
            sections.append(line[3:].strip())
    return sections
