#!/usr/bin/env python3
"""Optimize CLAUDE.md to stay under 150 lines."""

import sys
from pathlib import Path

# Add lib to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from lib.sidecar import has_marker, add_marker, count_lines, extract_sections


def optimize_claude_md(file_path: Path = None) -> None:
    """Optimize a CLAUDE.md file to stay under 150 lines.

    Args:
        file_path: Path to CLAUDE.md (defaults to ./CLAUDE.md)
    """
    if file_path is None:
        file_path = Path("CLAUDE.md")

    if not file_path.exists():
        print(f"❌ CLAUDE.md not found at {file_path}")
        print("   Run `/setup-starter` to create one")
        return

    content = file_path.read_text()
    original_lines = count_lines(content)

    if original_lines <= 150:
        print(f"✅ CLAUDE.md is already optimized ({original_lines}/150 lines)")
        return

    # Optimize the content
    optimized = _optimize_content(content)
    optimized_lines = count_lines(optimized)

    if has_marker(file_path):
        # Safe to overwrite - file was generated by our tools
        try:
            file_path.write_text(optimized)
            print(f"✨ CLAUDE.md optimized!")
            print(f"   Before: {original_lines} lines")
            print(f"   After:  {optimized_lines} lines")
            print(f"   Saved:  {original_lines - optimized_lines} lines")
        except Exception as e:
            print(f"❌ Error updating file: {e}")
    else:
        # File is custom - write to sidecar
        sidecar_path = Path(f"CLAUDE.md.setup-claude.md")
        optimized_with_marker = add_marker(optimized)
        try:
            sidecar_path.write_text(optimized_with_marker)
            print(f"📝 Optimized suggestion saved to: {sidecar_path}")
            print(f"   Original: {original_lines} lines")
            print(f"   Optimized: {optimized_lines} lines")
            print(f"   Review and merge manually if desired")
        except Exception as e:
            print(f"❌ Error creating suggestion: {e}")


def _optimize_content(content: str) -> str:
    """Optimize content by collapsing sections and removing redundancy."""
    lines = content.split("\n")
    optimized = []
    skip_next_empty = False
    previous_was_section = False

    for i, line in enumerate(lines):
        stripped = line.strip()

        # Skip multiple consecutive empty lines
        if not stripped:
            if skip_next_empty:
                continue
            skip_next_empty = True
            optimized.append(line)
            continue

        skip_next_empty = False

        # Check if this is a section header
        is_section = stripped.startswith("##")

        # Remove extra spacing between sections
        if is_section and previous_was_section and optimized and not optimized[-1].strip():
            optimized.pop()  # Remove the empty line before this section

        # Collapse verbose descriptions
        if "code" in stripped.lower() or "project" in stripped.lower():
            # Keep concise descriptions only
            if len(stripped) > 100 and not stripped.startswith("#"):
                stripped = stripped[:100] + "..."

        optimized.append(line)
        previous_was_section = is_section

    # Join back and remove trailing whitespace
    result = "\n".join(optimized).strip()

    # Remove marker if present (we'll re-add it)
    result = result.replace("<!-- Generated by /setup-claude-tools -->", "").strip()

    return result


def main():
    """Main entry point."""
    optimize_claude_md()


if __name__ == "__main__":
    main()
