#!/usr/bin/env python3
"""Enhanced optimizer: Enrich CLAUDE.md with comprehensive project context.

Instead of just trimming lines, this discovers:
- Project directory structure (src/, tests/, docs/, etc.)
- Documentation files and resources
- Build workflows and common commands
- Preserves user customizations across multiple runs
"""

import sys
from pathlib import Path

# Add lib to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from lib.sidecar import has_marker, add_marker, count_lines, extract_sections
from lib.discover import discover_directories, discover_documentation, discover_workflows
from lib.merge import (
    parse_claude_md, merge_sections, reconstruct_claude_md,
    extract_preservation_report
)
from lib.enrich import (
    generate_directories_section, generate_documentation_section,
    generate_workflows_section, estimate_content_lines
)


def optimize_claude_md(file_path: Path = None) -> None:
    """Optimize CLAUDE.md by enriching with project context.

    This is now a maintenance command that:
    1. Discovers actual project structure
    2. Finds documentation and workflows
    3. Merges discoveries with existing content
    4. Preserves user customizations
    5. Reports what was added/preserved

    Args:
        file_path: Path to CLAUDE.md (defaults to ./CLAUDE.md)
    """
    if file_path is None:
        file_path = Path("CLAUDE.md")

    if not file_path.exists():
        print(f"❌ CLAUDE.md not found at {file_path}")
        print("   Run `/setup-starter` to create one")
        return

    print("🔍 Analyzing project structure...")

    # Discover project information
    root_path = file_path.parent
    discovered_dirs = discover_directories(root_path)
    discovered_docs = discover_documentation(root_path)
    discovered_workflows = discover_workflows(root_path)

    # Parse existing CLAUDE.md
    existing_content = file_path.read_text()
    existing_sections = parse_claude_md(existing_content)
    original_lines = count_lines(existing_content)

    # Generate new sections based on discoveries
    generated_sections = _generate_sections_from_discoveries(
        discovered_dirs, discovered_docs, discovered_workflows
    )

    # Merge existing with generated (preserves user edits)
    merged_sections, preservation_report = merge_sections(
        existing_sections, generated_sections
    )

    # Reconstruct CLAUDE.md
    optimized = reconstruct_claude_md(merged_sections, include_marker=True)
    optimized_lines = count_lines(optimized)

    # Print report
    print()
    print("📊 Analysis Complete:")
    print(f"   📁 Directories discovered: {len(discovered_dirs)}")
    print(f"   📚 Documentation files: {len(discovered_docs)}")
    print(f"   🔧 Workflows found: {sum(len(v) for v in discovered_workflows.values())}")
    print()

    # Show what was discovered
    if discovered_dirs:
        print("✅ Key Directories Found:")
        for dir_name, desc in list(discovered_dirs.items())[:5]:
            print(f"   - {dir_name}/")
        if len(discovered_dirs) > 5:
            print(f"   ... and {len(discovered_dirs) - 5} more")
        print()

    if discovered_docs:
        print("📖 Documentation Found:")
        for doc_path, desc in list(discovered_docs.items())[:5]:
            print(f"   - {doc_path}")
        if len(discovered_docs) > 5:
            print(f"   ... and {len(discovered_docs) - 5} more")
        print()

    # Show preservation report
    if preservation_report:
        print(preservation_report)
        print()

    # Save the updated file
    if has_marker(file_path):
        # Safe to overwrite - file was generated by our tools
        try:
            file_path.write_text(optimized)
            print(f"✨ CLAUDE.md enriched and saved!")
            print(f"   Before: {original_lines} lines")
            print(f"   After:  {optimized_lines} lines")
            if optimized_lines > original_lines:
                print(f"   Added: {optimized_lines - original_lines} lines (comprehensive context)")
            else:
                print(f"   Optimized: {original_lines - optimized_lines} lines saved")
            print()
            print("💡 Tip: Run this command again after adding new directories or docs!")
        except Exception as e:
            print(f"❌ Error updating file: {e}")
    else:
        # File is custom - write to sidecar
        sidecar_path = Path(f"CLAUDE.md.setup-claude.md")
        try:
            sidecar_path.write_text(optimized)
            print(f"📝 Enriched version saved to: {sidecar_path}")
            print(f"   Original:  {original_lines} lines")
            print(f"   Enriched:  {optimized_lines} lines")
            print()
            print("   Your CLAUDE.md is custom (no generation marker).")
            print("   Review the suggestion above and merge manually if desired.")
        except Exception as e:
            print(f"❌ Error creating suggestion: {e}")


def _generate_sections_from_discoveries(
    discovered_dirs, discovered_docs, discovered_workflows
) -> dict:
    """Generate template sections from discoveries.

    Args:
        discovered_dirs: Dict of directory names to descriptions
        discovered_docs: Dict of doc paths to descriptions
        discovered_workflows: Dict of workflow types to commands

    Returns:
        Dict of section_name -> content
    """
    sections = {}

    # Add Key Directories section
    if discovered_dirs:
        sections['Key Directories'] = generate_directories_section(discovered_dirs)

    # Add Documentation section
    if discovered_docs:
        sections['Documentation & Resources'] = generate_documentation_section(discovered_docs)

    # Add Workflows section
    if discovered_workflows:
        sections['Common Workflows'] = generate_workflows_section(discovered_workflows)

    return sections


def main():
    """Main entry point."""
    optimize_claude_md()


if __name__ == "__main__":
    main()
