---
description: "Start with design questions before writing code."
---

<!-- Generated by /setup-claude -->

# /brainstorm

**Workflow:** **Explore** → Design → Plan → Branch → Write Tests + Implement → Commit → Gates → Finalize

Explore design and clarify requirements **before** any code is written.

## Hard Rules

- **DO NOT write, edit, or generate any code.** No files, no snippets, no pseudo-implementations.
- **DO NOT create a plan.** That is `/sk:write-plan`'s job.
- **DO NOT run build/test/lint commands.** You are in design mode only.
- You may **read** existing code to understand the current state, but nothing more.

## Steps

0. **Read context files first:**
   - If `tasks/spec.md` exists, read it first. Treat every acceptance criterion as a fixed constraint — do not re-ask questions the spec already answers. Note: "Spec found — requirements pre-defined. Exploring implementation approaches only."
   - If `tasks/findings.md` exists and has content, read it — summarize prior decisions
     and ask: extend, revise, or start fresh?
   - If `tasks/lessons.md` exists, read it in full. Apply every active lesson as a design
     constraint throughout this brainstorm — treat each prevention rule as a hard constraint
     when proposing approaches.
   - If `tasks/security-findings.md` exists and has audit results, skim for recurring
     patterns — factor security constraints into proposed approaches (e.g., if prior audits
     flagged missing input validation, ensure new designs account for it).

2. **Understand the request** — Ask clarifying questions about what the user wants. Do not assume. Cover:
   - What problem are we solving?
   - Who is it for?
   - What are the expected inputs/outputs or behaviors?
   - Are there constraints (performance, compatibility, existing patterns)?

3. **Explore the current codebase** (read-only) — Identify:
   - Relevant files, modules, and patterns already in place
   - How similar features are implemented today
   - Potential impact areas and dependencies

4. **Propose approaches** — Present 2–3 design options with trade-offs:
   - Approach name + 1-sentence summary
   - Pros and cons
   - Complexity estimate (small / medium / large)
   - Which existing patterns it follows or breaks

5. **Get alignment** — Ask the user which approach they prefer (or if they want a hybrid). Do not proceed without explicit approval on the direction.

5b. **requirements checklist:** After the user approves an approach, extract all requirements into an explicit numbered checklist:

   ```
   ## Requirements Checklist
   1. [ ] [Requirement extracted from discussion]
   2. [ ] [Requirement extracted from discussion]
   ...
   ```

   Then ask: *"Are all requirements captured? Any implicit assumptions or missing edge cases?"*

   Do not proceed to step 6 until the checklist is confirmed complete. When writing to `tasks/findings.md` in step 6, include this checklist as a `## Requirements Checklist` section.

6. **Record findings** — Write discoveries and the agreed-upon direction to `tasks/findings.md`:
   - Problem statement
   - Key decisions made
   - Chosen approach + rationale
   - Open questions (if any remain)

## When Done

1. Tell the user:
   > "Brainstorming complete. Findings saved to `tasks/findings.md`."
4. If step 2 (`/sk:frontend-design`) is next, ask: "Step 2 is `/sk:frontend-design` (optional). Run it or skip?"

**Do not proceed to planning or implementation yourself.** The user must explicitly invoke the next step.
