---
description: "Write a decision-complete plan into tasks/todo.md (no code yet)."
---

<!-- Generated by /setup-claude -->

# /write-plan

**Workflow:** Explore → Design → **Plan** → Branch → Write Tests + Implement → Commit → Gates → Finalize

Create a decision-complete plan **before** writing code.

## Steps

1. Ensure planning files exist:
   - `tasks/todo.md`
   - `tasks/findings.md`
   - `tasks/progress.md`
2. Read context files:
   - `tasks/findings.md` — requirements + discoveries; extract problem statement,
     constraints, and open questions explicitly into the plan
   - `tasks/lessons.md` — if it exists, apply all active lessons as constraints
     before writing any plan steps
3. Update `tasks/todo.md` with:
   - **Goal** (1–2 lines)
   - **Plan** as checkboxes (small, verifiable steps)
   - **Verification** commands (exact commands + expected outcomes)
   - **Acceptance criteria** (clear "done" conditions)
   - **Risks/unknowns** (anything still ambiguous)
3b. **Contracts-first check:** Scan the written plan in `tasks/todo.md` for these keywords: `API`, `endpoint`, `route`, `controller`, `backend`, `service`, `request`, `response`. If any are found, auto-generate `tasks/contracts.md` with:

   ```markdown
   # API Contracts — [task name]

   ## Endpoints

   | Method | Path | Auth | Description |
   |--------|------|------|-------------|
   | POST   | /api/example | Bearer | Description |

   ## Request / Response Shapes

   ### POST /api/example
   **Request:**
   ```json
   { "field": "type" }
   ```
   **Response (200):**
   ```json
   { "field": "type" }
   ```
   **Errors:** 400 (validation), 401 (unauthorized), 404 (not found)

   ## Auth Requirements

   [Describe auth method — Bearer token, session, API key, etc.]

   ## Mocking Boundary

   **Frontend mocks:** [what the frontend stubs out during isolated development]
   **Backend owns:** [what the backend implements — source of truth]
   ```

   Fill in the contract based on what the plan describes. If the plan is too vague for a specific field, write `[TBD — clarify before implementation]`.

   This file is the mandatory handshake for `/sk:team`. If no API keywords are found, skip this step silently.
4. **Consensus check (auto):**

   Scan `tasks/findings.md` and the task description for high-risk keywords:
   - **Auth/security:** `auth`, `authentication`, `authorization`, `permission`, `role`, `token`, `OAuth`, `2FA`, `session`, `password`
   - **Data safety:** `migration`, `schema`, `data loss`, `DROP`, `truncate`, `production data`, `seed`
   - **Payments:** `payment`, `billing`, `stripe`, `invoice`, `checkout`, `subscription`
   - **Public API:** `API contract`, `breaking change`, `backward compat`, `deprecat`
   - **Infrastructure:** `deploy`, `CI/CD`, `pipeline`, `environment variable`, `secret`, `credentials`

   If high-risk keyword found (and `--no-consensus` not passed):
   → Log: `[Write-plan] High-risk task — running architect + critic review.`
   → Architect (read-only): strongest argument against approach, one real tradeoff, architectural concerns.
   → Critic (read-only, after architect): are acceptance criteria testable? alternatives fairly dismissed?
   → Main context applies revisions. Max 2 rounds.

   If no high-risk keywords: skip to step 5.
   Manual overrides: `--consensus` forces the loop; `--no-consensus` skips it.

5. Present the final plan to the user and wait for approval.

## Rules
- No implementation until the plan is approved.
- If something is unclear, add a plan step to explore it first.
