---
description: "Automate releases: bump version, update CHANGELOG, create tag, push to GitHub"
---

<!-- Generated by /setup-claude -->

# /release

Automate the release process for your project.

## Hard Rules

- **DO NOT** release without reviewing CHANGELOG.md changes
- **DO NOT** proceed if CHANGELOG.md has no [Unreleased] section
- You **must** have a git remote origin (GitHub, GitLab, etc.)
- Version format must follow semantic versioning (e.g., v1.0.0, v0.2.0-beta)

## Steps

1. **Verify CHANGELOG.md** — Check that the [Unreleased] section has the changes you want to release. If not, update CHANGELOG.md first and commit.

2. **Run the release script** — This will:
   - Auto-detect: project name, current version, GitHub URL
   - Prompt for: new version number
   - Suggest: release title based on changes
   - Update: CHANGELOG.md (move [Unreleased] → [Version])
   - Update: version in CLAUDE.md (if it has a Version line)
   - Create: git commit with release message
   - Create: annotated git tag
   - Push: tag to GitHub (with confirmation at each step)

3. **Complete the release on GitHub** — The script will show you the GitHub releases link. Go there and:
   - Click "Create release from tag"
   - Use the suggested title
   - Copy the changelog section as release notes
   - Publish the release

## When Done

> "Release {version} completed! Check GitHub to finalize the release."

The tag is pushed and ready. Creating the GitHub release is a one-time manual step (you can automate this later with GitHub Actions if desired).

## Notes

- Each step (commit, tag, push) requires your confirmation
- You can skip any step and do it manually later
- The script works with any project type: Node, Python, Go, Rust, etc.
- Requires: CHANGELOG.md file with [Unreleased] section
